### ISSUE TITLE
[Feature request] Export parts for every instrument in the score.

### ISSUE THREAD

**Issue by AndroYD84** [kaisubr/mxcat#1]
SORRY DUMB QUESTION CAN DELETE

**Comment by kaisubr** [comment]
If you save the musicxml to mscx with MuseScore, I think MuseScore can export parts for each instrument already through the user interface, but for CLI you could try (if you had 6 staffs for example)
```
python mxcat.py file.mscx --staff 1:2:3:4:5:6 --output result.mscx
```
I coded this over a weekend for a personal project, so it's probably pretty buggy, and MuseScore probably does it better :)
